export enum ActionsType {
  ADD_COFFEE = 'ADD_COFFEE',
  REMOVE_COFFEE = 'REMOVE_COFFEE',
  INCREMENT_COFFEE = 'INCREMENT_COFFEE',
  DECREMENT_COFFEE = 'DECREMENT_COFFEE',
  CHECK_COFFEE = 'CHECK_COFFEE',
}
